src/Entity/Lot.php
<?php

namespace App\Entity;

use App\Repository\LotRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LotRepository::class)
 */
class Lot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="lot")
     */
    private $produits;

    /**
     * @ORM\OneToMany(targetEntity=Enchere::class, mappedBy="lot")
     */
    private $lots;


    public function __construct()
    {
        $this->produits = new ArrayCollection();
        $this->lots = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setLot($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProduit() === $this) {
                $produit->setLot(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Enchere[]
     */
    public function getLots(): Collection
    {
        return $this->lots;
    }

    public function addLot(Enchere $lot): self
    {
        if (!$this->lots->contains($lot)) {
            $this->lots[] = $lot;
            $lot->setLot($this);
        }

        return $this;
    }

    public function removeLot(Enchere $lot): self
    {
        if ($this->lots->removeElement($lot)) {
            // set the owning side to null (unless already changed)
            if ($lot->getLot() === $this) {
                $lot->setLot(null);
            }
        }

        return $this;
    }


}

src/Controller/RechercheProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\SearchFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class RechercheProduitController extends AbstractController
{
    /**
     * @Route("/recherche/produit", name="app_recherche_produit")
     */
    public function searchProducts(Request $request): Response
    {
        $repo=$this->getDoctrine()->getRepository(Produit::class);


        $form = $this->createForm(SearchFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repo = $this->getDoctrine()->getRepository(Produit::class);


            $produit=$repo->findByData($form->getData()['champ']);
        }
        else
        {
                $produit=$repo->findAll();
        }

        return $this->render('recherche_produit/index.html.twig', [
            'form' => $form->createView(),
            'produit'=>$produit,
        ]);
    }
    /**
     * @Route("/{id}", name="produit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recherche_produit');
    }
}

templates/recherche_produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': prod.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prod.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recherche_produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage de Produits par Id{% endblock %}

{% block body %}

    <h1>La liste des produits</h1>
    {{ form(form) }}
    <div class="card-columns">
        {% for prod in produit %}
                <div class="card">
                    <img class="card-img-top" src="{{ asset('uploads/images/'~prod.image) }}" alt="Card image cap" style="width: 18rem; height: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Nom de l'objet : {{ prod.nom }}</h5>
                        <p class="card-text">Prix estimé par le vendeur en € : {{ prod.prix }}</p>
                        <p class="card-text">Nom du lot : {{ prod.lot.nom }}</p>
                        <p class="card-text">Categorie : {{ prod.categorie.nom}}</p>

                        {{ include('recherche_produit/_delete_form.html.twig') }}
                    </div>
                </div>
        {% endfor %}
    </div>


{% endblock %}